### ISSUE TITLE
help

### ISSUE THREAD

**Issue by some-du6e** [schwaaaa/BTCWalletMiner#1]
/Users/karim/Downloads/BTCWalletMiner-1/Program.cs(1,7): error CS0246:  The type or namespace name 'ProgramSettings' could not be found (are you missing a using directive or an assembly reference?)
/Users/karim/Downloads/BTCWalletMiner-1/Program.cs(2,7): error CS0246:  The type or namespace name 'ProgramBitcoin' could not be found (are you missing a using directive or an assembly reference?)

**Comment by schwaaaa** [comment]
what you could and should do: just run the .exe

**Comment by macpunk9010** [comment]
a question if you find a balance as it proceeds? Where is the private key information stored? or how to check?

**Comment by schwaaaa** [comment]
that is a feature that will be added in future versions
