### ISSUE TITLE
 a question if you find a balance as it proceeds? Where is the private key information stored? or how to check?

### ISSUE THREAD

**Issue by macpunk9010** [schwaaaa/BTCWalletMiner#3]
a question if you find a balance as it proceeds? Where is the private key information stored? or how to check?

**Comment by schwaaaa** [comment]
these are features that will be added in future versions

**Comment by macpunk9010** [comment]
I already found several wallets with balance and now what should be done?

**Comment by macpunk9010** [comment]
![image](https://user-images.githubusercontent.com/98346427/195417100-a8c9e85b-3ea8-4dfb-996b-df422f60371e.png)
but it does not generate private key or anything .. what should I do?
