### ISSUE TITLE
solution

### ISSUE THREAD

**Issue by Talant047** [schwaaaa/BTCWalletMiner#9]
Hi.
 Please explain what does this value that turned out during the search mean - 

Address confirmed.
[+] 6DNV11DG6WUPEAAR1FOHOR4MYMX (0.19108768025722878 BTC)

**Comment by mclovinsdad** [comment]
it goes to the set BTC address that was asked at the start of the program

**Comment by Talant047** [comment]
> он идет на заданный адрес BTC, который был задан при запуске программы

And what to do with it? There is no description and no photographs so that you can start off in order to make some kind of analysis on finding. What should be and how should it look? It's all gloomy and sad.

**Comment by Talant047** [comment]
![image](https://github.com/schwaaaa/BTCWalletMiner/assets/50215875/6b5c0a7b-9dc2-4cb9-95bf-a518528e9c61)
Complete nonsense. It works both with and without the Internet and gives different indicators. Someone laughed at us well

**Comment by schwaaaa** [comment]
lmfao

**Comment by Talant047** [comment]
> лмфао

????????????????????????
